port: 8080
statusInterval: 10
servers:
  - url: "http://localhost:8082"
    statusURL: "http://localhost:8082/api/status"
  - url: "http://localhost:8083"
    statusURL: "http://localhost:8082/api/status"
